/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androiddynamic_DynamicModule */

#ifndef _Included_com_androiddynamic_DynamicModule
#define _Included_com_androiddynamic_DynamicModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androiddynamic_DynamicModule
 * Method:    check
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_androiddynamic_DynamicModule_check
  (JNIEnv *, jclass, jstring);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getRegisterAddress
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getGameNameStartAddress
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getGameSerialNumberStartAddress
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getSn
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getMini
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getPwd
	(JNIEnv *,jclass);

JNIEXPORT jint JNICALL Java_com_androiddynamic_DynamicModule_getKey
	(JNIEnv *,jclass);
/*
 * Class:     com_androiddynamic_DynamicModule
 * Method:    checkSignandPackageName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_androiddynamic_DynamicModule_checkSignandPackageName
  (JNIEnv *, jclass,jobject object);

#ifdef __cplusplus
}
#endif
#endif
