/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <GameCore.h>
#include <string.h>
#include <stdio.h>
#include <android/log.h>

#define LOGI(...) ((void)__android_log_print(ANDROID_LOG_INFO, "native-activity", __VA_ARGS__))
#define LOGW(...) ((void)__android_log_print(ANDROID_LOG_WARN, "native-activity", __VA_ARGS__))
#define LOGE(...) ((void)__android_log_print(ANDROID_LOG_ERROR, "native-activity", __VA_ARGS__))

#define sn 0 //序列号
#define mini 3 //mini号

/* Header for class com_androiddynamic_DynamicModule */



/*JNIEXPORT void JNICALL Java_com_androiddynamic_GameCore_checkSignture
  (JNIEnv *env, jclass clazz){
	jclass activityClass = (*env)->FindClass(env,"com/androiddynamic/MainActivity");
	jmethodID getSigntureID = (*env)->GetStaticMethodID(env,activityClass,"getSignture","()Ljava/lang/String;");
	jstring signture = (jstring)(*env)->CallStaticObjectMethod(env,activityClass,getSigntureID);
	char *realSignture = "308203773082025fa00302010202047aee256b300d06092a864886f70d01010b0500306b310b300906035504061302383631123010060355040813096775616e67646f6e6731123010060355040713096775616e677a686f753110300e060355040a1307636f6d70616e793110300e060355040b1307636f6d70616e793110300e0603550403130779756a696e66753020170d3133303932363130323733325a180f33303133303132373130323733325a306b310b300906035504061302383631123010060355040813096775616e67646f6e6731123010060355040713096775616e677a686f753110300e060355040a1307636f6d70616e793110300e060355040b1307636f6d70616e793110300e0603550403130779756a696e667530820122300d06092a864886f70d01010105000382010f003082010a0282010100954964cd9b6dd041794cae5886677dcb9ccec583b3e336fa43d61b66e95e1965d9c9bd708be8373484bd5451eb70212ef0195018b58fae3ed4753159ea301762aba782a2cdf66d23d15393e94f81b1258a97660ecfb478067770e235280ede135301246176a38455dd3797b9b1aaae273cb1085b3d50198ed3f351a745362492b6ae2ea2bf1a15025d44d3d428eb49fa3362c5d43220798ca6fb5cdf571ec9e6ad3e09b1ca4a6bae2954858e7e799d3cc8350cbfb44afc0294bd65056ef545128adeb6f2ba452d50da1a9d6c20151e2b63530c02638bddf95991eeca6e554bbe2c51f4dcf4bcf681aec188b9a2380aac721e98543125f1bdb14eebf3278e36af0203010001a321301f301d0603551d0e04160414b3634ab572298464f97bf4ab9a205bac0b0e4973300d06092a864886f70d01010b05000382010100179d7d985ac8d8ca182d641c7fe7a1a6ebd561231b456d81e03057dc4c9efc4dcb447078f70dbb5f043ad554545290f943ed881c95e232a8b66a0e57424c3acc2c85a255aa6eb044a296d1d607dac97c64a4e1f474dd6935082859e0aa865aa7c173569bb5ec841ac5c90492b3654afd2bc6ccba18cd40b4759715d403e223fd7fea39a3bd14b9242b53e726d57cd0ef91967c0b153adb6fda20a81355786d97b34757e4c781ffc4c96278e0c2b1436e74f345ac78e82f96e4105bdb11dae09fc0c630cb452952e5f1e6a0609d1c6c0cca5adb7aeab44ede961af8e00652aebeb35f7af187bfa102dbf8ad080bcfea198624ed08f1c10db482e75721dd76dacb";
	char *getSignture = (*env)->GetStringUTFChars(env,signture,0);
	if(strcmp(realSignture,getSignture) != 0)
	{
		LOGE("signture not pass");

		exit(0);
	}

	LOGE("signture pass");
}*/
//先混淆签名，将得到的签名混淆再比对，防止破解.rodata段
/*
JNIEXPORT void JNICALL Java_com_game_core_GameCore_checkSignture
  (JNIEnv *env, jclass clazz){

	char *encryptSign = "kh`jhkookh`jhjm>9hhkhjhihjhjhlo9==jmn:khh<hnhaj9`nl``n>oh<hihih:hmhhkhn:kih:khhahnhkmmhlhnikhjk`knkiijkhihhnhkmmhlh`ikhanoomnin=nonln>n=nokiijkhihhnhkmmhlhoikhanoomnin=noo9n`n>omkiihkhh=hnhkmmhlh9ikhonkn>n<ohnin=oakiihkhh=hnhkmmhlh:ikhonkn>n<ohnin=oakiihkhh=hnhkmmhlhkikhooaomn9nan=nnomkhjhioh<kikkkhkakjknkikhkjkokkkjm9i`h>kkkhkikkkhkikjkokikhkjkokkkjm9khn:kih:khhahnhkmmhlhnikhjk`knkiijkhihhnhkmmhlh`ikhanoomnin=nonln>n=nokiijkhihhnhkmmhlhoikhanoomnin=noo9n`n>omkiihkhh=hnhkmmhlh9ikhonkn>n<ohnin=oakiihkhh=hnhkmmhlh:ikhonkn>n<ohnin=oakiihkhh=hnhkmmhlhkikhooaomn9nan=nnomkh`jhijjkhh<hnhaj9`nl``n>oh<hihihihmhhhk`jhih>hhkh`jhih9hj`jhihihhamlanl;<a:n<<hlioal;9=m``nnoo<;:a;;=;m`k:k=kkn>9lk<ni:nn=am=ianm<a;a:<oh`:=`kokl`l:<mlmi=:ohjij=>hiamhi`:m`>9=k=<lomkima=9khionj9:9o`j9j;<>nn<jk<imkak=al>`i:ijm`9aonnh=;>:lo`hnoooh=jkmj`h=<=ikmkhijlnion9k`lmm<<koao:a:i999=jok;:ih`m:k<mhia`=<k>kmi9olmknjlaj:n9=j=9j:>i9imhjm<ll<k<lj`=:la>9kknj;m<lkjjhoa`;9n>:m;<>moi=;a=n9<k=ha:i;9l9n:9=jaml`m`=o=oaa<k;;`kmh;:>:ll9>;hjal:<nmhmn=>mlmij`9<=:n>j:9lmj<mh<9i9a<n;jhimi=j:nkmkh;hjnk`:<<>amaai==;9n=mml::=j;mi>l<;>l:;>n`i9=;i``:a9jk`h99;oji=a`mlkijm>i:<:il==:>kjo`=kn9>hjhkhihhhi9kjikhi>khi<hnhkmmi<h=hlinhlil:knkl9:mojja`lnl>ao:>l9:a9jhm:9;h:h=laokkhh<hnhaj9`nl``n>oh<hihih:hmhhhk`jhihihhioa<o<a`m9;`<`;9i`j<nli;o>=o9i9n=:<mnijki:lmn<`i=hkhmo<;l;a=>;l<;:lloho`>oh<::m>hlk9<mmlmlmjah>alk=<``i;am=jkj9`:nn9h=moljl;k9;;j;`m9jmm99n=:hll9jan<i<nho<9;ao;nl9l=i>lol<<nakmh`j`ma=h99`nm99o;iokmna::m=;`li9;m;ahlaj:knml9><j:;n;;:9i`;<lh:lomaoim<lhk=jjk><o>=9ka9k:<il:ajlj:mk=ojn<mo;<h=>aiano;h:imk9<:n><9jh9`ikmmo`n<ao:klomo=l;o`i>>;l;anjo`=h;j:ilkn=ol>klm9;o`=`j>an=lihm:<:ii<9=ha>;h;nkh;:lmjamj=m>i=n9hnha<i;n;h;;9m9<:o9=9:ll=<=ani9>`=hhnmj9=:=:km>o9>i`o:>9ihj<:>`9<h`h:;>=9ia`njl=<h`>i;ih<:l`j=omoji<<on<9;:";

	jclass activityClass = (*env)->FindClass(env,"com/androiddynamic/MainActivity");
	jmethodID getSigntureID = (*env)->GetStaticMethodID(env,activityClass,"getSignture","()Ljava/lang/String;");
	jstring signture = (jstring)(*env)->CallStaticObjectMethod(env,activityClass,getSigntureID);
	char *getSignture = (*env)->GetStringUTFChars(env,signture,0);
	char *head = getSignture;
	while(*getSignture != '\0')
	{
		*getSignture = *getSignture^88;
		getSignture++;
	}
	if(strcmp(encryptSign,getSignture) != 0)
	{
		LOGE("signture not pass");

		exit(0);
	}

	LOGE("signture pass");

}
*/
/*
 * Class:     com_androiddynamic_DynamicModule
 * Method:    checkSignture
 * Signature: (Ljava/lang/Object;)V
 */
/*
JNIEXPORT void JNICALL Java_com_game_core_GameCore_checkMySignture
  (JNIEnv *env, jclass clazz, jstring fullName){

	char *package_name = (*env)->GetStringUTFChars(env,fullName,0);
	jclass getSignture = (*env)->FindClass(env,"com/me/util/GetSignture");
	if(getSignture == NULL)
	{
		LOGE("getSignture null");
		exit(0);
	}
	jmethodID getSigntureID = (*env)->GetStaticMethodID(env,getSignture,"getApkSignInfo","(Ljava/lang/String;)Ljava/lang/String;");
	if(getSigntureID == NULL)
	{
		LOGE("getSigntureID null");
		exit(0);
	}

	char *sign = "308203773082025fa00302010202047aee256b300d06092a864886f70d01010b0500306b310b300906035504061302383631123010060355040813096775616e67646f6e6731123010060355040713096775616e677a686f753110300e060355040a1307636f6d70616e793110300e060355040b1307636f6d70616e793110300e0603550403130779756a696e66753020170d3133303932363130323733325a180f33303133303132373130323733325a306b310b300906035504061302383631123010060355040813096775616e67646f6e6731123010060355040713096775616e677a686f753110300e060355040a1307636f6d70616e793110300e060355040b1307636f6d70616e793110300e0603550403130779756a696e667530820122300d06092a864886f70d01010105000382010f003082010a0282010100954964cd9b6dd041794cae5886677dcb9ccec583b3e336fa43d61b66e95e1965d9c9bd708be8373484bd5451eb70212ef0195018b58fae3ed4753159ea301762aba782a2cdf66d23d15393e94f81b1258a97660ecfb478067770e235280ede135301246176a38455dd3797b9b1aaae273cb1085b3d50198ed3f351a745362492b6ae2ea2bf1a15025d44d3d428eb49fa3362c5d43220798ca6fb5cdf571ec9e6ad3e09b1ca4a6bae2954858e7e799d3cc8350cbfb44afc0294bd65056ef545128adeb6f2ba452d50da1a9d6c20151e2b63530c02638bddf95991eeca6e554bbe2c51f4dcf4bcf681aec188b9a2380aac721e98543125f1bdb14eebf3278e36af0203010001a321301f301d0603551d0e04160414b3634ab572298464f97bf4ab9a205bac0b0e4973300d06092a864886f70d01010b05000382010100179d7d985ac8d8ca182d641c7fe7a1a6ebd561231b456d81e03057dc4c9efc4dcb447078f70dbb5f043ad554545290f943ed881c95e232a8b66a0e57424c3acc2c85a255aa6eb044a296d1d607dac97c64a4e1f474dd6935082859e0aa865aa7c173569bb5ec841ac5c90492b3654afd2bc6ccba18cd40b4759715d403e223fd7fea39a3bd14b9242b53e726d57cd0ef91967c0b153adb6fda20a81355786d97b34757e4c781ffc4c96278e0c2b1436e74f345ac78e82f96e4105bdb11dae09fc0c630cb452952e5f1e6a0609d1c6c0cca5adb7aeab44ede961af8e00652aebeb35f7af187bfa102dbf8ad080bcfea198624ed08f1c10db482e75721dd76dacb";
	char *getSign;
	jstring jPackageName = (*env)->NewStringUTF(env,package_name);
	jstring signture = (jstring)(*env)->CallStaticObjectMethod(env,getSignture,getSigntureID,jPackageName);
	if(signture == NULL)
	{
		LOGE("signture null");
		exit(0);
	}
	getSign = (*env)->GetStringUTFChars(env,signture,0);
	if(strcmp(sign,getSign) != 0)
	{
		LOGE("signture not equal");
		exit(0);
	}
}
*/

JNIEXPORT void JNICALL Java_com_game_core_GameCore_checkSignandPackageName
  (JNIEnv * env, jclass clazz, jobject object)
{
	if(object == NULL)
	{
		LOGE("null pointer");
		exit(0);
	}
	char *sign = "3082037f30820267a0030201020204296d2a59300d06092a864886f70d01010b0500306f310e300c060355040613056368696e613111300f060355040813086e69656368656e673111300f060355040713086e69656368656e673111300f060355040a13086e69656368656e673111300f060355040b13086e69656368656e673111300f060355040313086e69656368656e673020170d3134303730343039353832385a180f33303133313130343039353832385a306f310e300c060355040613056368696e613111300f060355040813086e69656368656e673111300f060355040713086e69656368656e673111300f060355040a13086e69656368656e673111300f060355040b13086e69656368656e673111300f060355040313086e69656368656e6730820122300d06092a864886f70d01010105000382010f003082010a0282010100846c9a3f785e5624ca874ab34a1a0ecbdae39531a4daa0d78e2aa21dd1fa3b849959195aaaae5a9825f87173075743bc3f9a4a99491cc37ecbbffc07b33391f9a363dede8176068e77cf98bad8ed5800ece55ad3ed4594de1242f8317f862abd104342b0b0364fe275ccc81fb4e5a825824846b8833366a36c687f2addbee7400d56edf7276fd2914416fe18ef5208ed46da94bb564f4052b1ab1b2bb135c20a4f9f992cb71ecc556867a07c553cc08f581beda15649c2cfd261e77e61e236de16ca8f8d81dae3f8380463635bd45e58d2ce143a3ee084e8a76304df0bc8a30323861345118ce13abbfb3ac631b25141e8a4600a93dbebbeef0b043965c278790203010001a321301f301d0603551d0e041604140cb527b66c3155927dbcd941a3fcad4687cb1cca300d06092a864886f70d01010b050003820101001400bca4f42ff3a71a51677b399d0403bed047c612ceae6a7d06e271c6f2999662f1109a61537b8229948b19abb75aec16bd70b95932658b33be75df33cc6bc59686fb1c934d5b177a6b64ce8ab912a9da04e21b64b8283581e7109d8d8363f65f6f5435248d7b19b78f5ee7fbf56e8f4d6d1bec6f7d3855719d27ee7f5b0c5fceaca619747bf65b7f511aff41dba6a9cefb15ce8676bb1b3131975dd4c1eb4c13c9f58da4ab0d86fbdb72d8279fd4752da7fff30f60b28773062d2a56a76756aa414ac5bf57d7ea17b935b5f07de0d461d1b7995a47afd555ffdf2411355d236f8f7b5078ccb7eb123cbe2090b2fa021f1df1718762a11c3320628b1f96b295";

	//char *str = (*env)->GetStringUTFChars(env,string,0);

	//获取MainActivity的class
	jclass activityClass = (*env)->GetObjectClass(env,object);
	//获取getPackageManager方法ID
	jmethodID getPackageManagerID = (*env)->GetMethodID(env,activityClass,"getPackageManager","()Landroid/content/pm/PackageManager;");
	jobject packageManager = (*env)->CallObjectMethod(env,object,getPackageManagerID);
	if(packageManager == NULL)
	{
		LOGE("packageManager is null");
		exit(0);
	}
	//得到PackageManager的class对象
	jclass packageManagerClass = (*env)->FindClass(env,"android/content/pm/PackageManager");
	//获取getPackageInfo方法ID
	jmethodID getPackageInfo = (*env)->GetMethodID(env,packageManagerClass,"getPackageInfo","(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;");

	jmethodID getPackageName = (*env)->GetMethodID(env,activityClass,"getPackageName","()Ljava/lang/String;");

	jstring packageName = (jstring)(*env)->CallObjectMethod(env,object,getPackageName);
	//获取packageInfo对象
	jobject packageInfo = (*env)->CallObjectMethod(env,packageManager,getPackageInfo,packageName,64);
	jclass packageInfoClass = (*env)->FindClass(env,"android/content/pm/PackageInfo");

	jfieldID signID = (*env)->GetFieldID(env,packageInfoClass,"signatures","[Landroid/content/pm/Signature;");
	jobjectArray signFieldArray = (jobjectArray)(*env)->GetObjectField(env,packageInfo,signID);
	jobject signField = (*env)->GetObjectArrayElement(env,signFieldArray,0);
	jclass signatureClass = (*env)->FindClass(env,"android/content/pm/Signature");
	jmethodID toCharStringID = (*env)->GetMethodID(env,signatureClass,"toCharsString","()Ljava/lang/String;");
	jobject signCharString = (*env)->CallObjectMethod(env,signField,toCharStringID);
	//LOGE("ABCDE");
	char *getSign = (*env)->GetStringUTFChars(env,(jstring)signCharString,0);

	//释放本地引用
	(*env)->DeleteLocalRef(env,packageManager);
	(*env)->DeleteLocalRef(env,signFieldArray);
	(*env)->DeleteLocalRef(env,signField);
	(*env)->DeleteLocalRef(env,signCharString);

	if(strcmp(getSign,sign) != 0)
	{
		exit(0);
		//exit(env,object);
	}
}


/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getRegisterAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_game_core_GameCore_getRegisterAddress
  (JNIEnv * env, jclass clazz)
{
	return (jint)12;
}

/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getGameNameStartAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_game_core_GameCore_getGameNameStartAddress
  (JNIEnv * env, jclass clazz)
{
	return (jint)25;
}

/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getGameSerialNumberStartAddress
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_game_core_GameCore_getGameSerialNumberStartAddress
  (JNIEnv * env, jclass clazz)
{
	return (jint)42;
}

/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getSn
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_game_core_GameCore_getSn
  (JNIEnv * env, jclass clazz)
{
	return (jlong)0;
}

/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getMini
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_game_core_GameCore_getMini
  (JNIEnv * env, jclass clazz)
{
	return (jint)3;
}

/*
 * Class:     com_me_android_serialport_api_SerialPort
 * Method:    getPwd
 * Signature: ()B
 */

JNIEXPORT jbyte JNICALL Java_com_game_core_GameCore_getPwd
  (JNIEnv * env, jclass clazz)
{
	return (jbyte)'a';
}

JNIEXPORT jint JNICALL Java_com_game_core_GameCore_getKey
	(JNIEnv * env,jclass clazz)
{
	return (jint)10086;
}


/*JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* reserved)
{
	JNIEnv* env = NULL;
	jint result = -1;

	if ((*vm)->GetEnv(vm, (void**) &env, JNI_VERSION_1_4) != JNI_OK) {
		return -1;
	}
	assert(env != NULL);

	if (!registerNatives(env)) {//注册
		return -1;
	}
	 success -- return valid version number
	result = JNI_VERSION_1_4;

	return result;
}*/

/*
 * Class:     com_me_game_core_GameCore
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
/*JNIEXPORT jstring JNICALL Java_com_me_game_core_GameCore_encrypt
  (JNIEnv *env, jclass clazz, jstring str)
{
	jclass clz = (*env)->FindClass(env,"com/me/game/core/GameCore");
	jmethodID methodID = (*env)->GetStaticMethodID(env,clz,"encryptString","(Ljava/lang/String;)Ljava/lang/String;");

	jstring jstr = (jstring)(*env)->CallStaticObjectMethod(env,clz,methodID,str);

	//(*env)->DeleteLocalRef(env,clz);
	//(*env)->DeleteLocalRef(env,methodID);

		return jstr;
}*/

/*
 * Class:     com_me_game_core_GameCore
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
/*JNIEXPORT jstring JNICALL Java_com_me_game_core_GameCore_decrypt
  (JNIEnv *env, jclass clazz, jstring str)
{
	jclass clz = (*env)->FindClass(env,"com/me/game/core/GameCore");
	jmethodID methodID = (*env)->GetStaticMethodID(env,clz,"decryptString","(Ljava/lang/String;)Ljava/lang/String;");

	jstring jstr = (jstring)(*env)->CallStaticObjectMethod(env,clz,methodID,str);

	//(*env)->DeleteLocalRef(env,clz);
	//(*env)->DeleteLocalRef(env,methodID);

		return jstr;
}*/



